/**
 * Copyright (c) 2022 Boston Dynamics, Inc.  All rights reserved.
 *
 * Downloading, reproducing, distributing or otherwise using the SDK Software
 * is subject to the terms and conditions of the Boston Dynamics Software
 * Development Kit License (20191101-BDSDK-SL).
 */


#pragma once

namespace bosdyn {

namespace common {

    // File containing bosdyn.api.graph_nav.graph proto
    const std::string kGraphFile = "graph";

    // File containing bosdyn.api.autowalk.walk proto
    // File is in mission directory
    const std::string kAutowalkFile = "autogenerated.walk";

    // File containing bosdyn.api.mission.node proto
    // File is in mission directory
    const std::string kNodeFile = "autogenerated";

    // Autowalk metadata file name
    const std::string kAutowalkMetadataFile = "autowalk_metadata";

    // Directory containing waypoint snapshots
    const std::string kWaypointSnapshotDir = "waypoint_snapshots";

    // Directory containing edge snapshots
    const std::string kEdgeSnapshotDir = "edge_snapshots";

    // Directory containing walk and node files
    const std::string kMissionsDir = "missions";



} // namespace common
} // namespace bosdyn